# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-04-14 15:45
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0015_auto_20180217_0041'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrackSuggestion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coverLocation', models.URLField(max_length=1000, null=True)),
                ('title', models.CharField(max_length=1000)),
                ('year', models.IntegerField(null=True)),
                ('composer', models.CharField(max_length=1000, null=True)),
                ('performer', models.CharField(max_length=1000, null=True)),
                ('number', models.IntegerField(null=True)),
                ('bpm', models.IntegerField(null=True)),
                ('lyrics', models.CharField(max_length=42000, null=True)),
                ('comment', models.CharField(max_length=10000, null=True)),
                ('discNumber', models.IntegerField(null=True)),
                ('artist', models.CharField(max_length=10000, null=True)),
                ('album', models.CharField(max_length=10000, null=True)),
                ('genre', models.CharField(max_length=10000, null=True)),
                ('trackReference', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Track')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
