# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-04-21 15:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_tracksuggestion'),
    ]

    operations = [
        migrations.AddField(
            model_name='tracksuggestion',
            name='albumTotalDisc',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='tracksuggestion',
            name='albumTotalTrack',
            field=models.IntegerField(null=True),
        ),
    ]
